services:
  mongo:
    image: mongo:8.0.11
    container_name: mongo-collectors
    restart: unless-stopped
    user: root
    ports:
      - 27018:27017
    volumes:
      - ./volumes/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: collectors
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: movies
    networks:
      - collectors-network

  influxdb:
    image: influxdb:1.11.8
    container_name: influxdb-collectors
    restart: unless-stopped
    user: root
    ports:
      - 8087:8086
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_USER: collectors
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_DB: collectorsDB
    networks:
      - collectors-network

  grafana:
    image: grafana/grafana:10.4.19
    container_name: grafana-collectors
    restart: unless-stopped
    user: root
    ports:
      - 3001:3000
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    networks:
      - collectors-network
    depends_on:
      - mongo
      - influxdb

networks:
  collectors-network:
    external: true
